FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY . .

RUN dotnet restore WifiActivationOrchestration.sln

CMD ["dotnet", "test", "WifiActivationOrchestration.sln", "--configuration", "Release", "--no-restore"]